xm:
  #Trajectory Controllers ---------------------------------------
  right_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint_lift
      - joint_waist
      - joint_big_arm
      - joint_forearm
      - joint_wrist_pitching
      - joint_wrist_rotation

    constraints:
      goal_time: 0.5                  
      stopped_velocity_tolerance: 0.02

    gains:
      joint_lift: {p: 2000.0, i: 1.0, d: 150.0, i_clamp: 1}
      
      joint_waist: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}    
      
      joint_big_arm: {p: 300.0, i: 0.01, d: 10.0, i_clamp: 1}
      
      joint_forearm: {p: 200.0, i: 0.01, d: 10.0, i_clamp: 1}    
      
      joint_wrist_pitching: {p: 500.0, i: 0.01, d: 0.09, i_clamp: 1}
      
      joint_wrist_rotation: {p: 1.0, i: 0.0, d: 10.0, i_clamp: 1}

    state_publish_rate:  25           
    action_monitor_rate: 30            
    stop_trajectory_duration: 0
